language: go

sudo: required

go:
    - 1.7

before_install:
    - sudo apt-get install protobuf-compiler
    - go get -v google.golang.org/grpc
    - go get -v github.com/golang/protobuf/proto
    - go get -v github.com/golang/protobuf/protoc-gen-go
    - go get -v github.com/gogo/protobuf/protoc-gen-gofast
    - go get github.com/mattn/goveralls

install:
    - go get -t -v ./...

script:
    - go test -v ./...

after_success:
    - $HOME/gopath/bin/goveralls -service=travis-ci
